# The name of the workflow
name: build
on: [push, pull_request]

jobs:
  coverage:
    name: Test and publish test coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@code-climate-update
      - uses: actions/setup-node@code-climate-update
        with:
          node-version: "12"
      - run: npm install
      - uses: paambaati/codeclimate-action@v2.4.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CodeClimateReporterId }}
        with:
          coverageCommand: npm run coverage
